language: generic
sudo:required
services: 
  - docker

before_install:
  - docker build -t abishr12/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abishr12/react-test npm test

after_success:
  - docker build -t abishr12/multi-client ./client
  - docker build -t abishr12/multi-nginx ./nginx
  - docker build -t abishr12/multi-server ./server
  - docker build -t abishr12/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push  abishr12/multi-client
  - docker push  abishr12/multi-nginx
  - docker push  abishr12/multi-server
  - docker push  abishr12/multi-worker